standards.yml: Use PHP 7.4
```
▸ Run vendor/bin/php-cs-fixer fix --dry-run --rules=@Symfony src/
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 8.0.*.
Current PHP version: 8.0.0.
PHP CS Fixer is not able run on PHP 8.0.0 due to bug in PHP tokenizer (https://bugs.php.net/bug.php?id=80462).
Update PHP version to unblock execution.
Error: Process completed with exit code 1.
```